# Generated by Django 5.1.1 on 2024-09-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dean', '0002_department_role_profile_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
