# Generated by Django 5.1.1 on 2024-09-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dean', '0003_alter_profile_department_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('cict', 'CICT'), ('bme', 'BME')], default='cict', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('pc', 'PC')], default='faculty', max_length=10),
        ),
    ]
